name: Monadist
favicon: null
layout_spectrum: 0.67608
typography_spectrum: 0.423
title: Simple Pet Care Tips For Lesser Stress
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72706398-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
