name: Monadist
favicon: null
layout_spectrum: 0.91152
typography_spectrum: 0.65177
title: Simple Pet Care Tips For Lesser Stress
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72706398-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e3e52'
    - '#b1d2e1'
    - '#d8edf8'
    - '#72a8b2'
    - '#487c86'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
