name: Monadist
favicon: null
layout_spectrum: 0.7346324089448899
typography_spectrum: 0.9217333318665624
title: Simple Pet Care Tips For Lesser Stress
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72706398-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.838468664791435
  lightness: 0.3488682913593948
  saturation: 0.9835322378203273
  rhythmicContrast: 0.9675096336286515
purpose: []
